services:
  newapp:
    container_name: clinic-appointment-dev
    image: clinic-appointment-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # <-- NEW PORT
    environment:
      MONGO_URI: mongodb://moscrm:ClinicDB%40166091@81.196.46.41:27017/clinicdb_test?authSource=admin
      NODE_ENV: development
    restart: unless-stopped
    networks:
      - new-app-network

networks:
  new-app-network:

