services:
  newapp:
    container_name: clinic-appointment-new
    image: clinic-appointment-new
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"   # <-- NEW PORT
    environment:
      MONGO_URI: mongodb://moscrm:${MONGO_PASSWORD}@clinic-mongo:27017/clinicdb?authSource=admin
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - new-app-network

networks:
  new-app-network:

